import { RecipeModel } from '../models/recipe.model';

export const recipesDatabase: Record<string, RecipeModel> = {
  1: {
    id: 1,
    title: 'Spaghetti Carbonara',
    description: 'Klasična talijanska pasta s kremastim umakom od jaja, parmezana i pancete.',
    category: 'Pasta',
    difficulty: 'Srednje',
    totalTime: '30 min',
    prepTime: '10 min',
    cookTime: '20 min',
    image: '',
    author: { name: 'Mario Rossi', rank: 'Profesionalni kuhar', avatar: '' },
    nutrition: { calories: 520, protein: 22, carbs: 65, fat: 18 },
    servings: 4,
    rating: 4.8,
    reviews: 234,
    likes: 1205,
    views: 8500,
    saves: 430,
    tags: ['pasta', 'talijanska', 'brzo', 'klasika', 'carbonara'],
    ingredients: [
      { name: 'Spaghetti', amount: '400g' },
      { name: 'Panceta ili guanciale', amount: '150g' },
      { name: 'Jaja (cijela)', amount: '2 kom' },
      { name: 'Žumanjci', amount: '2 kom' },
      { name: 'Parmigiano Reggiano', amount: '80g, svježe naribanog' },
      { name: 'Crni papar', amount: 'po ukusu' },
      { name: 'Sol', amount: 'za kuhanje paste' },
    ],
    steps: [
      {
        number: 1,
        title: 'Kuhanje paste',
        description:
          'U veliku posudu zakipite jako slanu vodu. Dodajte spaghetti i kuhajte prema uputama na pakovanju dok ne budu al dente. Sačuvajte šalicu vode od kuhanja paste.',
        time: '10 min',
        image: '',
      },
      {
        number: 2,
        title: 'Prženje pancete',
        description:
          'U velikoj tavi na srednje jakoj vatri ispržite narezanu pancetu dok ne postane hrskava i zlatna. Maknite s vatre i ostavite da se malo ohladi.',
        time: '8 min',
        image: '',
      },
      {
        number: 3,
        title: 'Priprema umaka',
        description:
          'U zdjeli umutite jaja, žumanjke i naribani parmezan. Dobro posolite i popaprite. Ovo je ključni korak — umak mora biti kremast, ne jajast.',
        time: '5 min',
        image: '',
      },
      {
        number: 4,
        title: 'Spajanje',
        description:
          'Skuhanu pastu dodajte u tavu s pancetom (vatru ugasite!). Prelijte umakom od jaja i brzo miješajte. Dodajte malo vode od paste da dobijete kremast umak. Poslužite odmah.',
        time: '5 min',
        image: '',
      },
    ],
    tips: [
      'Nikada nemojte koristiti vrhnje — autentična carbonara ga ne sadrži.',
      'Vatra mora biti ugašena prije dodavanja jaja da se ne skuhaju.',
      'Voda od kuhanja paste je tajna kremastog umaka — ne preskočite ovaj korak.',
      'Koristite svježe naribani parmezan, ne onaj iz vrećice.',
    ],
    comments: [
      {
        id: 1,
        author: 'Ivana K.',
        rating: 5,
        date: '15. ožujka 2025.',
        text: 'Savršen recept! Konačno sam napravila pravu carbonaru bez vrhnja. Obitelj je bila oduševljena.',
        likes: 24,
      },
      {
        id: 2,
        author: 'Tomislav B.',
        rating: 4,
        date: '2. travnja 2025.',
        text: 'Odličan recept, jedino što sam koristio običnu slaninu jer nisam mogao naći pancetu. Svejedno je ispalo ukusno.',
        likes: 11,
      },
    ],
  },

  2: {
    id: 2,
    title: 'Grčka salata',
    description: 'Svježa mediteranska salata s fetom, maslinama i povrćem.',
    category: 'Salate',
    difficulty: 'Lako',
    totalTime: '15 min',
    prepTime: '15 min',
    cookTime: '0 min',
    image: '',
    author: { name: 'Ana Kovač', rank: 'Amaterski kuhar', avatar: '' },
    nutrition: { calories: 180, protein: 8, carbs: 12, fat: 12 },
    servings: 2,
    rating: 4.5,
    reviews: 89,
    likes: 430,
    views: 3200,
    saves: 180,
    tags: ['salata', 'mediteranska', 'zdrava', 'vegeterijansko', 'brzo'],
    ingredients: [
      { name: 'Krastavci', amount: '2 kom' },
      { name: 'Rajčice', amount: '3 kom' },
      { name: 'Crveni luk', amount: '1/2 kom' },
      { name: 'Crne masline', amount: '100g' },
      { name: 'Feta sir', amount: '150g' },
      { name: 'Maslinovo ulje', amount: '3 žlice' },
      { name: 'Origano', amount: '1 žličica' },
      { name: 'Sol i papar', amount: 'po ukusu' },
    ],
    steps: [
      {
        number: 1,
        title: 'Priprema povrća',
        description:
          'Krastavce narežite na krupnije kockice, rajčice na osmine, a crveni luk na tanke polukrugove. Sve složite u veliku zdjelu.',
        time: '10 min',
        image: '',
      },
      {
        number: 2,
        title: 'Slaganje i začinjavanje',
        description:
          'Dodajte masline i na krupno narezani feta sir. Prelijte maslinovim uljem, pospite origanom te solju i paprom. Lagano promiješajte i odmah poslužite.',
        time: '5 min',
        image: '',
      },
    ],
    tips: [
      'Koristite zrele, slatke rajčice za najbolji okus.',
      'Nemojte previše miješati — komadi fete trebaju ostati na komadu.',
      'Salatu poslužite odmah — puštanjem stoji postaje vodenasta.',
    ],
    comments: [
      {
        id: 1,
        author: 'Maja S.',
        rating: 5,
        date: '20. travnja 2025.',
        text: 'Jednostavno i ukusno! Pravim ovo stalno za ljetne večere.',
        likes: 15,
      },
      {
        id: 2,
        author: 'Dario M.',
        rating: 4,
        date: '5. svibnja 2025.',
        text: 'Klasika koja nikad ne razočara. Dodao sam malo limunovog soka i bilo je odlično.',
        likes: 8,
      },
    ],
  },

  3: {
    id: 3,
    title: 'Tiramisu',
    description: 'Klasični talijanski desert s mascarponeom, espressom i kakaom.',
    category: 'Deserti',
    difficulty: 'Teško',
    totalTime: '45 min',
    prepTime: '30 min',
    cookTime: '0 min',
    image: '',
    author: { name: 'Luca Ferrari', rank: 'Profesionalni slastičar', avatar: '' },
    nutrition: { calories: 380, protein: 6, carbs: 42, fat: 20 },
    servings: 8,
    rating: 4.9,
    reviews: 312,
    likes: 2100,
    views: 12000,
    saves: 950,
    tags: ['desert', 'talijanski', 'kava', 'mascarpone', 'klasika'],
    ingredients: [
      { name: 'Mascarpone', amount: '500g' },
      { name: 'Jaja', amount: '4 kom (odvojena)' },
      { name: 'Šećer', amount: '100g' },
      { name: 'Espresso kava', amount: '300ml, ohlađena' },
      { name: 'Savoiardi keksi (ladyfinger)', amount: '200g' },
      { name: 'Kakao u prahu', amount: 'za posipanje' },
      { name: 'Amaretto (opcionalno)', amount: '2 žlice' },
    ],
    steps: [
      {
        number: 1,
        title: 'Priprema kreme',
        description:
          'Žumanjke umutite sa šećerom dok smjesa ne postane blijedožuta i kremasta. Dodajte mascarpone i lagano miješajte dok ne dobijete glatku kremu.',
        time: '10 min',
        image: '',
      },
      {
        number: 2,
        title: 'Tučeni bjelanjci',
        description:
          'Bjelanjke tucite u čvrstog snijega. Lagano umiješajte u mascarpone kremu koristeći pokrete odozdo prema gore kako biste zadržali volumen.',
        time: '8 min',
        image: '',
      },
      {
        number: 3,
        title: 'Namakanje keksa',
        description:
          'Ohlaenu kavu (s amarettom ako koristite) ulijte u plitku posudu. Savoiardi kekse brzo umočite — sekunda s jedne, sekunda s druge strane. Ne natapajte previše!',
        time: '5 min',
        image: '',
      },
      {
        number: 4,
        title: 'Slaganje i hlađenje',
        description:
          'U posudi izmjenjujte slojeve keksa i kreme. Završite slojem kreme i obilno pospite kakaom. Pokrijte i stavite u hladnjak minimalno 4 sata, idealno preko noći.',
        time: '10 min',
        image: '',
      },
    ],
    tips: [
      'Tiramisu je bolji sutradan — okusi se spoje i desert se "slegne".',
      'Nemojte predugo namakati kekse — postanu kašasti.',
      'Koristite svježa jaja dobrog kvaliteta jer se ne kuhaju.',
      'Za intenzivniji okus kave, dodajte malo espresso praška u kafu.',
    ],
    comments: [
      {
        id: 1,
        author: 'Petra L.',
        rating: 5,
        date: '10. ožujka 2025.',
        text: 'Najbolji tiramisu kojeg sam ikad napravila! Sve kolege na poslu su tražile recept.',
        likes: 47,
      },
      {
        id: 2,
        author: 'Robert H.',
        rating: 5,
        date: '28. ožujka 2025.',
        text: 'Savršen recept. Jedino što sam dodao malo više amaretta i bilo je božanstveno.',
        likes: 32,
      },
    ],
  },

  4: {
    id: 4,
    title: 'Američke palačinke',
    description: 'Mekane i pahuljaste palačinke savršene za doručak.',
    category: 'Doručak',
    difficulty: 'Lako',
    totalTime: '20 min',
    prepTime: '5 min',
    cookTime: '15 min',
    image: '',
    author: { name: 'Sara Johnson', rank: 'Food blogger', avatar: '' },
    nutrition: { calories: 320, protein: 9, carbs: 55, fat: 8 },
    servings: 4,
    rating: 4.6,
    reviews: 156,
    likes: 780,
    views: 5600,
    saves: 310,
    tags: ['doručak', 'američki', 'slatko', 'pahuljasto', 'brzo'],
    ingredients: [
      { name: 'Brašno', amount: '200g' },
      { name: 'Prašak za pecivo', amount: '2 žličice' },
      { name: 'Sol', amount: '1/2 žličice' },
      { name: 'Šećer', amount: '2 žlice' },
      { name: 'Mlijeko', amount: '240ml' },
      { name: 'Jaje', amount: '1 kom' },
      { name: 'Maslac (otopljeni)', amount: '2 žlice' },
      { name: 'Vanilija', amount: '1 žličica' },
    ],
    steps: [
      {
        number: 1,
        title: 'Suhi sastojci',
        description:
          'U većoj zdjeli pomiješajte brašno, prašak za pecivo, sol i šećer. Napravite udubinu u sredini.',
        time: '3 min',
        image: '',
      },
      {
        number: 2,
        title: 'Mokri sastojci',
        description:
          'U posebnoj zdjeli umutite mlijeko, jaje, otopljeni maslac i vaniliju. Ulijte u udubinu suhih sastojaka i lagano pomiješajte — smjesa smije imati grudice, nemojte previše miješati!',
        time: '3 min',
        image: '',
      },
      {
        number: 3,
        title: 'Pečenje',
        description:
          'Zagrijte tavu na srednje jakoj vatri i lagano premažite maslacem. Za svaku palačinku ulijte oko 60ml smjese. Pecite dok se ne pojave mjehuriće na površini (oko 2 minute), zatim okrenite i pecite još 1-2 minute.',
        time: '12 min',
        image: '',
      },
    ],
    tips: [
      'Tajna pahuljastih palačinki je ne miješati previše — grudice su normalne i poželjne.',
      'Tava mora biti dobro zagrijana prije nego počnete peći.',
      'Poslužite odmah s javorovim sirupom, svježim voćem ili Nutellom.',
    ],
    comments: [
      {
        id: 1,
        author: 'Kristina P.',
        rating: 5,
        date: '8. travnja 2025.',
        text: 'Konačno palačinke koje su stvarno pahuljaste! Moja djeca ih obožavaju.',
        likes: 29,
      },
      {
        id: 2,
        author: 'Filip J.',
        rating: 4,
        date: '14. travnja 2025.',
        text: 'Super recept! Dodao sam borovnice u tijesto i ispalo je savršeno.',
        likes: 18,
      },
    ],
  },

  5: {
    id: 5,
    title: 'Pad Thai',
    description: 'Popularno tajlandsko jelo s rezancima, tofu ili škampima i umakom od kikirikija.',
    category: 'Azijska kuhinja',
    difficulty: 'Srednje',
    totalTime: '25 min',
    prepTime: '10 min',
    cookTime: '15 min',
    image: '',
    author: { name: 'Tom Chen', rank: 'Azijska kuhinja specijalist', avatar: '' },
    nutrition: { calories: 450, protein: 20, carbs: 58, fat: 15 },
    servings: 2,
    rating: 4.7,
    reviews: 198,
    likes: 950,
    views: 7200,
    saves: 420,
    tags: ['azijsko', 'tajlandsko', 'rezanci', 'wok', 'začinjeno'],
    ingredients: [
      { name: 'Rice noodles (široki)', amount: '200g' },
      { name: 'Škampi ili tofu', amount: '200g' },
      { name: 'Jaja', amount: '2 kom' },
      { name: 'Fish sauce', amount: '3 žlice' },
      { name: 'Tamarind pasta', amount: '2 žlice' },
      { name: 'Šećer', amount: '1 žlica' },
      { name: 'Mladi luk', amount: '3 stabljike' },
      { name: 'Mljeveni kikiriki', amount: '50g' },
      { name: 'Limetina korica i sok', amount: '1 limeta' },
      { name: 'Bean sprouts', amount: '100g' },
    ],
    steps: [
      {
        number: 1,
        title: 'Namakanje rezanaca',
        description:
          'Rezance namočite u hladnoj vodi 30 minuta, ili u vrućoj vodi 10 minuta. Trebaju biti mekani ali još čvrsti — dokuhat će se u woku.',
        time: '10 min',
        image: '',
      },
      {
        number: 2,
        title: 'Priprema umaka',
        description:
          'Pomiješajte fish sauce, tamarind pastu i šećer. Probajte i prilagodite — umak treba biti balans slatkog, kiselog i slanog.',
        time: '3 min',
        image: '',
      },
      {
        number: 3,
        title: 'Kuhanje u woku',
        description:
          'Zagrijte wok na visokoj temperaturi. Dodajte ulje i ispržite škampe/tofu. Odmaknite na stranu, razbijte jaja i kratko scramblajte. Dodajte rezance i umak, sve dobro promiješajte.',
        time: '8 min',
        image: '',
      },
      {
        number: 4,
        title: 'Posluživanje',
        description:
          'Dodajte bean sprouts i mladi luk, kratko promiješajte. Poslužite s mljevenim kikirikijem, svježe iscijeđenom limetom i ljutom paprikom po ukusu.',
        time: '2 min',
        image: '',
      },
    ],
    tips: [
      'Visoka temperatura woka je ključna — "wok hei" daje pravi azijski okus.',
      'Ne prepunite wok — kuhajte u manjim serijama ako je potrebno.',
      'Tamarind pastu možete zamijeniti s malo limunovog soka i smeđeg šećera.',
    ],
    comments: [
      {
        id: 1,
        author: 'Lea N.',
        rating: 5,
        date: '22. travnja 2025.',
        text: 'Bolji od restorana! Teško je naći dobre azijske restorane ovdje, pa ovo je spas.',
        likes: 38,
      },
      {
        id: 2,
        author: 'Marko T.',
        rating: 4,
        date: '1. svibnja 2025.',
        text: 'Odličan recept. Malo teže naći tamarind pastu, ali vrijedi truda.',
        likes: 21,
      },
    ],
  },

  6: {
    id: 6,
    title: 'Penne Arrabiata',
    description: 'Ljuta talijanska pasta s pikantnim umakom od rajčice i češnjaka.',
    category: 'Pasta',
    difficulty: 'Lako',
    totalTime: '25 min',
    prepTime: '5 min',
    cookTime: '20 min',
    image: '',
    author: { name: 'Marco Bianchi', rank: 'Talijanska kuhinja entuzijast', avatar: '' },
    nutrition: { calories: 420, protein: 14, carbs: 72, fat: 10 },
    servings: 3,
    rating: 4.4,
    reviews: 112,
    likes: 560,
    views: 4100,
    saves: 220,
    tags: ['pasta', 'talijanska', 'ljuto', 'vegeterijansko', 'brzo'],
    ingredients: [
      { name: 'Penne pasta', amount: '350g' },
      { name: 'Pelati (cijele rajčice)', amount: '400g' },
      { name: 'Češnjak', amount: '4 režnja' },
      { name: 'Ljuta papričica (peperoncino)', amount: '2 kom' },
      { name: 'Maslinovo ulje', amount: '4 žlice' },
      { name: 'Sol', amount: 'po ukusu' },
      { name: 'Svježi peršin', amount: 'šaka' },
    ],
    steps: [
      {
        number: 1,
        title: 'Priprema umaka',
        description:
          'U tavi zagrijte maslinovo ulje na srednje jakoj vatri. Dodajte nasjeckani češnjak i nasjeckane ljute papričice, pržite dok češnjak ne omekša i ne zamiriše (oko 2 minute).',
        time: '5 min',
        image: '',
      },
      {
        number: 2,
        title: 'Kuhanje umaka',
        description:
          'Dodajte pelate, prstima ih zgnječite u tavi. Posolite i kuhajte na umjerenoj vatri 15 minuta dok umak ne zgusne. Na kraju dodajte nasjeckani peršin.',
        time: '15 min',
        image: '',
      },
      {
        number: 3,
        title: 'Kuhanje paste i spajanje',
        description:
          'Paralelno skuhajte penne u jako slanoj vodi al dente. Procijedite (sačuvajte malo vode) i dodajte u umak. Promiješajte, po potrebi dodajte malo vode od paste.',
        time: '12 min',
        image: '',
      },
    ],
    tips: [
      'Arrabiata znači "ljuta" — ne štedite na papričicama!',
      'Dobar maslinovo ulje je osnova odličnog umaka.',
      'Peršin dodajte tek na kraju da zadrži svježu aromu.',
    ],
    comments: [
      {
        id: 1,
        author: 'Nikolina R.',
        rating: 4,
        date: '18. travnja 2025.',
        text: 'Jednostavno i ukusno. Dodala sam malo više češnjaka jer ga obožavamo.',
        likes: 14,
      },
      {
        id: 2,
        author: 'Bruno K.',
        rating: 5,
        date: '30. travnja 2025.',
        text: 'Savršen recept za brzu večeru. Moj novi favorit!',
        likes: 9,
      },
    ],
  },
};
